### ISSUE TITLE
Cutscenes not working after building the project

### ISSUE THREAD

**Issue by zwietabak** [gagdiez/PACgd#4]
After building the project for either Windows or Linux the cutscenes aren't playing anymore.
Do you have any suggestions about a fix?

**Comment by gagdiez** [comment]
Interesting, I will try to reproduce this error. Do they work before you build it, i.e. when running the game from the editor?

**Comment by zwietabak** [comment]
Yes, they do work when running the game from the editor.

**Comment by gagdiez** [comment]
I found the error, you simply need to add a filter to export non-resources files (since the cut-scenes are .txt, they are not taking into consideration by Godot during the export).

Add the `**/*.txt` filter, or you can be more specific and add `path/to/cutscenes/*.txt`

**Comment by zwietabak** [comment]
Now it's working! Thank you very much for your time and help!
